allowBuilds:
  '@parcel/watcher': false
  '@sentry/node-cpu-profiler': false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@sentry/core@10.75.2'
  - '@sentry/node-core@10.75.2'
  - '@sentry/node@10.75.2'
  - '@sentry/opentelemetry@10.75.2'
  - '@sentry/profiling-node@10.75.2'
  - '@sentry/server-utils@10.75.2'
  - dotenv@18.0.3
  - supertest@7.3.0
